// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.normandy.user_id", "1c53ecaa-a303-4223-8559-59a199dedc40");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1576658969);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1576659089);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1576658999);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 2520);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1576658938);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 87);
user_pref("browser.newtabpage.activity-stream.impressionId", "{5f9bbb8f-1429-4563-aaf2-4787c4ea7f28}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1576658993858");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1576660778858");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1576658942512");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1576662542512");
user_pref("browser.search.region", "VN");
user_pref("browser.slowStartup.averageTime", 5407);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20191205184924");
user_pref("browser.startup.homepage_override.mstone", "71.0");
user_pref("browser.startup.lastColdStartupCheck", 1576658940);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1576658940896");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "71.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "6bbf85f65bde454fbb41f21c56358ae9");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "71.0");
user_pref("extensions.lastPlatformVersion", "71.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"a2c67da6-fe63-4931-9bc3-b7340891dfc8\",\"screenshots@mozilla.org\":\"6dada909-8ef8-4187-aea3-a32e7bbc75af\",\"webcompat-reporter@mozilla.org\":\"b834b9a1-bc12-43f9-b33a-2b9d3d7ea39c\",\"webcompat@mozilla.org\":\"b0464325-4c5c-48b4-9eac-54f453007b2f\",\"default-theme@mozilla.org\":\"0dcb1367-3280-4048-af7a-5a23f4a510ab\",\"google@search.mozilla.org\":\"f5215386-60f7-4e83-9b50-cdbf9ef74a81\",\"amazondotcom@search.mozilla.org\":\"b43d7034-d1cc-4c78-9e5d-234cfab4cff2\",\"bing@search.mozilla.org\":\"5502fc14-5c73-4e3a-b16b-e81ce5bae419\",\"ddg@search.mozilla.org\":\"f8811fa4-f967-44f2-8ea9-0067448e4f21\",\"ebay@search.mozilla.org\":\"44bdf5f8-d4ce-4a42-92f5-00e0232d9492\",\"twitter@search.mozilla.org\":\"43d1ef41-3411-4a37-804f-5f5a662f8ff2\",\"wikipedia@search.mozilla.org\":\"41081b0f-6463-4aa8-9ce4-b62547f3af7d\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "46ebdb7a-5744-4c61-a007-58ad850f8a90");
user_pref("security.sandbox.plugin.tempDirSuffix", "3bfa5088-384a-4a5f-98c1-5b03ea385a69");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1576658938);
user_pref("toolkit.telemetry.cachedClientID", "221f8f88-86e3-411d-b570-90b54a5a31c0");
user_pref("toolkit.telemetry.previousBuildID", "20191205184924");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.extendedTriplets.experiment", "control");
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("trailhead.firstrun.interruptsExperiment", "full_page_e");
