- AINEWS:
    id_type: href
    browser_profile: ''
    web_url: https://artificialintelligence-news.com
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths:
    - .//article[@id="post-area"]//ul[@class="shareaholic-share-buttons shareaholic-no-margin-padding-important"]
    - .//div[@id="content-main"]/p/strong/..
    - .//div[@id="content-main"]/div[@class="post-tags"]
    - .//div[@id="content-main"]/div[@class="mvp-related-posts left relative"]
    - .//div[@id="content-main"]/div[@id="comments-button"]
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - .//img/@src
    - .//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - ''
    - ''
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: false
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: https://artificialintelligence-news.com
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //time[@itemprop="datePublished"]
    - //time[@itemprop="datePublished"]
    topic_type: href
    maximum_url: 10
    get_detail_content: true
    content_xpath:
    - //article[@id="post-area"]
    - //article[@id="post-area"]
    text_xpath:
    - .//div[@id="content-main"]/p
    image_box_xpath:
    - ./div[@id="post-feat-img"]
    image_title_xpath: []
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: https://pbs.twimg.com/profile_images/882601763387449346/D_9Fb-Oz.jpg
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://artificialintelligence-news.com
    minimum_topic_length: 4
    tags: []
