- Người Lao Động:
    id_type: href
    browser_profile: ''
    web_url: https://nld.com.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths:
    - //node()[@class='VCSortableInPreviewMode alignCenter active']
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - //node()[@class='contentbody']//img/@src
    - //node()[@class='contentbody']//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //node()[@class='sapo-detail']/text()
    - //node()[@class='sapo-detail']/text()
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: https://nld.com.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //node()[@class='pdate fl']
    - //node()[@class='pdate fl']
    topic_type: href
    maximum_url: 30
    get_detail_content: true
    content_xpath:
    - //node()[@class='contentbody']
    - //node()[@class='contentbody']
    text_xpath:
    - //node()[@class='contentbody']/div[@class='content-news-detail']/p
    - //node()[@class='author fr']
    image_box_xpath:
    - //node()[@class='VCSortableInPreviewMode']
    image_title_xpath:
    - //node()[@class='VCSortableInPreviewMode']/div[2]/p/text()/..
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: http://ainewsobj.6112cf5e.viettel-cdn.vn/bangtin/91496ee9-48ff-4cd1-a3fd-8582ffcff7e8_small.jpg
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://nld.com.vn
    minimum_topic_length: 4
    browser_timeout: 60
    prevent_auto_redirect: false
