- Báo  Ấp Bắc điện tử:
    id_type: href
    browser_profile: ''
    web_url: http://baoapbac.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths:
    - //node()[@id='content']/node()[1]
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - //node()[@id='content']//img/@src
    - //node()[@id='content']//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - (//node()[@class='content']/p[not(iframe)])[1]//text()|//node()[@class='content']/node()[1]//strong/text()
    - (//node()[@class='content']/p[not(iframe)])[1]//text()|//node()[@class='content']/node()[1]//strong/text()
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: http://baoapbac.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //node()[@id='current-date']
    - //node()[@id='current-date']
    topic_type: href
    maximum_url: 30
    get_detail_content: true
    content_xpath:
    - //node()[@id='content']
    - //node()[@id='content']
    text_xpath:
    - //node()[@id='content']/div/p
    - //node()[@id='content']/div[not(table)]
    - //node()[@id='content']/p
    image_box_xpath:
    - //node()[@class='image center']
    - //node()[@class='center image']
    image_title_xpath:
    - //node()[@class='image center']/tbody/tr[2]/td
    - //node()[@class='image center']/tbody/tr[2]/td/p
    - //node()[@class='center image']/tbody/tr[2]/td
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: http://baoapbac.vn/dataimages/201706/original/images1354438_apbac.png
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: http://baoapbac.vn
    minimum_topic_length: 4
    browser_timeout: 60
    prevent_auto_redirect: false
