- Nhân Đạo & Đời Sống:
    id_type: href
    browser_profile: ''
    web_url: http://baonhandao.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths: []
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - //node()[@class='article-content content-post']//img/@src
    - //node()[@class='article-content content-post']//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //node()[@class='article-sapo']/text()
    - //node()[@class='article-sapo']/text()
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: http://baonhandao.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //node()[@class='publish-date dim w160']/a
    - //node()[@class='publish-date dim w160']/a
    topic_type: href
    maximum_url: 10
    get_detail_content: true
    content_xpath:
    - //node()[@class='article-content content-post']
    - //node()[@class='article-content content-post']
    text_xpath:
    - //node()[@class='article-content content-post']/p[not(img)]
    - //node()[@class='article-content content-post']/div/p[not(img)]
    image_box_xpath:
    - //node()[@class='caption']
    image_title_xpath:
    - //node()[@class='caption']/figcaption
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: http://ainewsobj.6112cf5e.viettel-cdn.vn/bangtin/0e4adad5-b4e7-42d6-850a-f1edec25ae6b_small.jpg
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: http://baonhandao.vn
    minimum_topic_length: 4
    browser_timeout: 60
    prevent_auto_redirect: false
