- Báo  Lai Châu điện tử:
    id_type: href
    browser_profile: ''
    web_url: http://www.baolaichau.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths: []
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - //node()[@class='desc body']//img/@src
    - //node()[@class='desc body']//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //node()[@class='desc sapo']/text()
    - //node()[@class='desc sapo']/text()
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: http://www.baolaichau.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //node()[@class='text-muted']
    - //node()[@class='text-muted']
    topic_type: href
    maximum_url: 10
    get_detail_content: true
    content_xpath:
    - //node()[@class='desc body']
    - //node()[@class='desc body']
    text_xpath:
    - '//node()[@class=''desc body'']/p[@style=''text-align: justify;'']'
    image_box_xpath:
    - //node()[@class='desc body']/p/a/..
    image_title_xpath:
    - //node()[@class='desc body']/p/a/../following-sibling::p/em
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: http://www.baolaichau.vn/uploaded/logo/2019/05/03/Logo-Dau-Bao_1551943362125-111111111111_1551946934116_1556871516502.jpg
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: http://www.baolaichau.vn
    minimum_topic_length: 4
    browser_timeout: 60
    prevent_auto_redirect: false
