- Báo điện tử Xây dựng:
    id_type: href
    browser_profile: ''
    web_url: http://www.baoxaydung.com.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: true
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths:
    - //node()[@class='content_article entry-content clearfix']/p[1]
    - //node()[@class='content_article entry-content clearfix']/table
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - //node()[@class='content_article entry-content clearfix']//img/@src
    - //node()[@class='content_article entry-content clearfix']//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //node()[@class='content_article entry-content clearfix']/p[1]/strong/text()
    - //node()[@class='content_article entry-content clearfix']/p[1]/strong/text()
    - //node()[@class='content_article entry-content clearfix']/p/strong/span/text()
    - //node()[@class='content_article entry-content clearfix']/p/strong/span/text()
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: http://www.baoxaydung.com.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //node()[@class='publish_date']
    - //node()[@class='publish_date']
    topic_type: href
    maximum_url: 20
    get_detail_content: true
    content_xpath:
    - //node()[@class='content_article entry-content clearfix']
    - //node()[@class='content_article entry-content clearfix']
    text_xpath:
    - //node()[@class='content_article entry-content clearfix']/p[not(span)]
    - //node()[@class='content_article entry-content clearfix']/p[not(contains(@style,
      'center'))]
    image_box_xpath:
    - '//node()[@class=''content_article entry-content clearfix'']/p[@style=''text-align:
      center;'']'
    image_title_xpath:
    - '//node()[@class=''content_article entry-content clearfix'']/p[@style=''text-align:
      center;'']/span'
    - '//node()[@class=''content_article entry-content clearfix'']/p[@style=''text-align:
      center;'']/following-sibling::p/span'
    - //node()[@style='color:#0000cd;']
    - //node()[@style='color:#0000cd;']/br/following-sibling::node()
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: http://www.baoxaydung.com.vn/modules/frontend/themes/images/vn/logo.png?v=2.620180210204013
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: http://www.baoxaydung.com.vn
    minimum_topic_length: 4
    browser_timeout: '30'
    prevent_auto_redirect: false
