- VnMedia:
    id_type: href
    browser_profile: ''
    web_url: http://vnmedia.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths:
    - //node()[@class='content-detail']/p[1]
    - //node()[@class='content-detail']/table[@border='1']
    - //node()[@class='content-detail']/div[1]
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - //node()[@class='content-detail']//img/@src
    - //node()[@class='content-detail']//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //node()[@class='content-detail']/p[1]/strong/text()
    - //node()[@class='content-detail']/div[1]/strong/text()
    - //node()[@class='content-detail']/p[1]/strong/text()]
    - //node()[@class='content-detail']/div[1]/strong/text()]
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: http://vnmedia.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //node()[@class='date']
    - //node()[@class='date']
    topic_type: href
    maximum_url: 30
    get_detail_content: true
    content_xpath:
    - //node()[@class='content-detail']
    - //node()[@class='content-detail']
    text_xpath:
    - //node()[@class='content-detail']/p
    - //node()[@class='content-detail']/p/span
    - //node()[@class='content-detail']/p/strong
    - //node()[@class='content-detail']/p/span/strong
    - //node()[@class='content-detail']/p/span/em
    - //node()[@class='content-detail']/p/em
    - //node()[@class='content-detail']/div/p
    - //node()[@class='content-detail']/div/strong
    - //node()[@class='content-detail']/div
    image_box_xpath:
    - //table[@class='image center']
    - //node()[@id='photo_type_content']
    image_title_xpath:
    - //figcaption/span
    - //figcaption
    - //node()[@class='des']
    - //node()[@class='image_desc']
    - //node()[@class='image center']/tbody/tr/td
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: http://ainewsobj.6112cf5e.viettel-cdn.vn/bangtin/a5531b11-23c9-4920-aacc-ded7ed3772a6_small.jpg
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: http://vnmedia.vn
    minimum_topic_length: 4
    browser_timeout: '30'
    prevent_auto_redirect: false
