- Báo Pháp luật TP.HCM điện tử:
    id_type: href
    browser_profile: ''
    web_url: https://plo.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths:
    - //node()[@class="widget adwidget"]
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - //node()[@id="abdf"]//img/@src
    - //node()[@id="abdf"]//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //node()[@class="sapo cms-desc"]/div/text()
    - //node()[@class="sapo cms-desc"]/div/text()
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: https://plo.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - (//time)[2]
    - (//time)[2]
    topic_type: href
    maximum_url: 30
    get_detail_content: true
    content_xpath:
    - //node()[@id="main_detail"]
    - //node()[@id="main_detail"]
    text_xpath:
    - //node()[@id="abody"]/p[not(contains(@class, "photo"))]
    - //node()[@id="main_detail"]/node()[contains(@style, "right")]
    image_box_xpath:
    - //node()[@class="item-photo"]
    image_title_xpath:
    - //node()[@class="item-photo"]/em
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: https://upload.wikimedia.org/wikipedia/commons/2/22/B%C3%A1o_Ph%C3%A1p_Lu%E1%BA%ADt_TP.HCM.jpg
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://plo.vn
    minimum_topic_length: 4
    browser_timeout: 60
    prevent_auto_redirect: false
