- Kinh Tế Nông Thôn:
    id_type: href
    browser_profile: ''
    web_url: https://kinhtenongthon.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: true
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths:
    - //node()[@class='hidden-print banner middle_post mb15 text-center']
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - //node()[@class='article-detail']//img/@src
    - //node()[@class='article-detail']//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //node()[@class='mb0']/text()
    - //node()[@class='mb0']/text()
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: https://kinhtenongthon.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - (//node()[@class='friendly'])[1]
    - (//node()[@class='friendly'])[1]
    topic_type: href
    maximum_url: 30
    get_detail_content: true
    content_xpath:
    - //node()[@class='article-detail']
    - //node()[@class='article-detail']
    text_xpath:
    - //node()[@class='article-detail']/p
    image_box_xpath:
    - //figure/img/..
    image_title_xpath:
    - //figure/img/../following-sibling::p/em
    - //figure/img/../figcaption/cite
    - //figure/em
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: http://ainewsobj.6112cf5e.viettel-cdn.vn/bangtin/54da5501-6bad-4308-8332-0ea197fedfbd_small.jpg
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://kinhtenongthon.vn
    minimum_topic_length: 4
    browser_timeout: 60
    prevent_auto_redirect: false
