- Báo điện tử Gia đình và Xã hội:
    id_type: href
    browser_profile: ''
    web_url: http://giadinh.net.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths:
    - //node()[@class='subbottomnew']
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - //node()[@class='content-new clear']//img/@src
    - //node()[@class='content-new clear']//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //node()[@class='detail-sp']//text()
    - //node()[@class='detail-sp']//text()
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: http://giadinh.net.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //node()[@class='title-detail']/p/span
    - //node()[@class='title-detail']/p/span
    topic_type: href
    maximum_url: 30
    get_detail_content: true
    content_xpath:
    - //node()[@class='content-new clear']
    - //node()[@class='content-new clear']
    text_xpath:
    - //node()[@class='content-new clear']/p
    - //node()[@class='tplCaption']/tbody/tr[2]/td/p
    - //node()[@class='desc_cation']/p
    - //node()[@class='FmsArticleBoxStyle-Content image_desc']/span
    image_box_xpath:
    - //node()[@type='Photo']
    image_title_xpath:
    - //node()[@data-placeholder='[nhập chú thích]']
    - //node()[@data-placeholder='[nhập chú thích]']/em
    - //node()[@type='Photo']/following-sibling::p/em
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: https://vinads.vn/wp-content/uploads/2018/11/z1.png
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: http://giadinh.net.vn
    minimum_topic_length: 4
    browser_timeout: 60
    prevent_auto_redirect: false
