- Báo điện tử Công lý:
    id_type: href
    browser_profile: ''
    web_url: https://congly.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths:
    - //node()[@class='news-dscontent']/table
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - //node()[@class='news-dscontent']//img/@src
    - //node()[@class='news-dscontent']//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //node()[@class='news-detail-summary']//text()
    - //node()[@class='news-detail-summary']//text()
    get_publish_date_as_crawl_date: false
    browser_fast_load: false
    skip_repeat_topic: true
    use_browser: true
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: https://congly.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //node()[@class='date-top']
    - //node()[@class='date-top']
    topic_type: href
    maximum_url: 20
    get_detail_content: true
    content_xpath:
    - //node()[@class='news-dscontent']
    - //node()[@class='news-dscontent']
    text_xpath:
    - //node()[@class='news-dscontent']/p[not(contains(@style, 'center'))]
    image_box_xpath:
    - //node()[@class='news-dscontent']/p//img/ancestor::p
    image_title_xpath:
    - //node()[@class='news-dscontent']/p//img/ancestor::p/following-sibling::p[contains(@style,
      'center')]/em/span
    - //node()[@class='news-dscontent']/p//img/ancestor::p/following-sibling::p[contains(@style,
      'center')]/span/em
    - //node()[@class='news-dscontent']/p//img/ancestor::p/following-sibling::p[contains(@style,
      'center')]/span/em/span
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: https://congly.vn/webskins/skins/news/images/logo-congly.png
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://congly.vn
    minimum_topic_length: 4
    browser_timeout: 60
    prevent_auto_redirect: false
