- Báo Hà Tĩnh điện tử:
    id_type: href
    browser_profile: ''
    web_url: https://baohatinh.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths:
    - //node()[@class='drelated']
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - ' //node()[@id=''main-detail'']//img/@src'
    - ' //node()[@id=''main-detail'']//img/@src'
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //node()[@class='sapo_detail']/text()
    - //node()[@class='sapo_detail']/text()
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: https://baohatinh.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //node()[@class='date_news']/span
    - //node()[@class='date_news']/span
    topic_type: href
    maximum_url: 30
    get_detail_content: true
    content_xpath:
    - //node()[@id='main-detail']
    - //node()[@id='main-detail']
    text_xpath:
    - ' //node()[@id=''main-detail'']/p[@class=''pBody'' or @class=''pAuthor'']'
    image_box_xpath:
    - //node()[@id='main-detail']/p[@class='pBody pCenter']
    image_title_xpath:
    - //node()[@class='pBody pCenter']/i
    - //node()[@class='pBody pCenter']/i/em
    - //node()[@class='iCaption']
    - //node()[@class='iCaption']/em
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: https://cdn.baohatinh.vn/cdn/apps/cms/baohatinh/logo/baohatinh.png
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://baohatinh.vn
    minimum_topic_length: 4
    browser_timeout: 60
    prevent_auto_redirect: false
