- Báo Sài Gòn giải phóng online:
    id_type: href
    browser_profile: ''
    web_url: http://www.sggp.org.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths:
    - //table[@class='notification' or @class='notification pull-right' or @class='quotes
      pull-right']
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - .//img/@src
    - .//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //div[@class='summary cms-desc']
    - //div[@class='summary cms-desc']
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: http://www.sggp.org.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //div[@class='meta-info']//time
    - //div[@class='meta-info']//time
    topic_type: href
    maximum_url: 30
    get_detail_content: true
    content_xpath:
    - //div[@class='content cms-body']
    - //div[@class='content cms-body']
    text_xpath:
    - .//p[text()]
    - .//p//span[text()]
    - .//div[not (descendant::img)][text()]
    - .//div[not (descendant::img)]//span[text()]
    image_box_xpath:
    - .//div[@class='full-img']
    image_title_xpath:
    - ./span[@class='fig'][text()]
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: http://static.sggp.org.vn/web/app_themes/img/logo.png
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: http://www.sggp.org.vn
    minimum_topic_length: 4
    browser_timeout: 60
    prevent_auto_redirect: false
