- Báo điện tử Đại biểu nhân dân:
    id_type: href
    browser_profile: ''
    web_url: http://daibieunhandan.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths: []
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - //node()[@class='NewsContent']//img/@src
    - //node()[@class='NewsContent']//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //div[@class='NewsAbstract']/text()
    - //div[@class='NewsAbstract']/text()
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: http://daibieunhandan.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //div[@class='NewsDate']
    - //div[@class='NewsDate']
    topic_type: href
    maximum_url: 30
    get_detail_content: true
    content_xpath:
    - //node()[@class='NewsContent']
    - //node()[@class='NewsContent']
    text_xpath:
    - //node()[@class='NewsContent']/p
    image_box_xpath:
    - '//table[@style=''margin-bottom: 8px; width: 450px; margin-top: 8px;'']'
    - '//node()[@style=''margin-top: 8px; width: 450px; margin-bottom: 8px;'']'
    - //node()[@class='NewsContent']/p[img]
    image_title_xpath:
    - '//em[@style=''''font-size: 11px;'''']'
    - '//node()[@style=''font-size: 11px;'']'
    - //node()[@class='NewsContent']/p[img]/following-sibling::p[contains(@style,
      'center')]//text()/..
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: http://daibieunhandan.vn/ONA_BDT/0/CHINHTRI-XAHOI/2009/Thang10/01-mau-ten-29109-300.jpg
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: http://daibieunhandan.vn
    minimum_topic_length: 4
    browser_timeout: 60
    prevent_auto_redirect: false
