- Đầu Tư:
    id_type: href
    browser_profile: ''
    web_url: https://baodautu.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths: []
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - //node()[@id='content_detail_news']//img/@src
    - //node()[@id='content_detail_news']//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //node()[@class='sapo_detail']/text()
    - //node()[@class='sapo_detail']/text()
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: https://baodautu.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //node()[@class='time_detail f14']
    - //node()[@class='time_detail f14']
    topic_type: href
    maximum_url: 10
    get_detail_content: true
    content_xpath:
    - //node()[@id='content_detail_news']
    - //node()[@id='content_detail_news']
    text_xpath:
    - //node()[@id='content_detail_news']/p
    image_box_xpath:
    - //node()[@class='MASTERCMS_TPL_TABLE']
    image_title_xpath:
    - //node()[@class='MASTERCMS_TPL_TABLE']/tbody/tr[2]/td
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: http://ainewsobj.6112cf5e.viettel-cdn.vn/bangtin/be14b8d9-efcc-4a30-89c6-6a504e80c387_small.jpg
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://baodautu.vn
    minimum_topic_length: 4
    browser_timeout: 60
    prevent_auto_redirect: false
