- Thế Giới & Việt Nam:
    id_type: href
    browser_profile: ''
    web_url: https://baoquocte.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths:
    - //node()[@class='__MB_ARTICLE_A']
    - //node()[@class='__mb_article_in_image']
    - //node()[@class='fb-page fb_iframe_widget']
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - //node()[@class='viewsDtailContent']//img/@src
    - //node()[@class='viewsDtailContent']//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //node()[@class='f-16']//text()
    - //node()[@class='f-16']//text()
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: https://baoquocte.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //node()[@class='dateUp']/span
    - //node()[@class='dateUp']/span
    topic_type: href
    maximum_url: 30
    get_detail_content: true
    content_xpath:
    - //node()[@class='viewsDtailContent']
    - //node()[@class='viewsDtailContent']
    text_xpath:
    - //node()[@class='viewsDtailContent']/p
    image_box_xpath:
    - //node()[@class='MASTERCMS_TPL_TABLE']
    image_title_xpath:
    - ./tbody/tr[2]/td
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: http://ainewsobj.6112cf5e.viettel-cdn.vn/bangtin/a9f425b8-824b-4a81-83f3-bf5a8d7057be_small.jpg
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://baoquocte.vn
    minimum_topic_length: 4
    browser_timeout: 60
    prevent_auto_redirect: false
