- Doanh Nhân Sài Gòn:
    id_type: href
    browser_profile: ''
    web_url: https://doanhnhansaigon.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: true
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths:
    - //node()[@class='box_see_more']
    - //node()[@class='social-img' or @class='box_quote']
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - //node()[@class='fck_detail']//img/@src
    - //node()[@class='fck_detail']//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //node()[@class='description']/text()
    - //node()[@class='description']/text()
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: https://doanhnhansaigon.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //node()[@class='time']
    - //node()[@class='time']
    topic_type: href
    maximum_url: 30
    get_detail_content: true
    content_xpath:
    - //node()[@class='fck_detail']
    - //node()[@class='fck_detail']
    text_xpath:
    - //node()[@class='fck_detail']/p
    image_box_xpath:
    - //node()[@class='fck_detail']/table
    image_title_xpath:
    - //node()[@class='fck_detail']/table/following-sibling::table//p[@class='Image']
    - //node()[@class='fck_detail']/table/following-sibling::table//p[@class='Image']/em
    - //node()[@class='fck_detail']/table//p[@class='Image']
    - //node()[@class='fck_detail']/table//p[@class='Image']/em
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: http://ainewsobj.6112cf5e.viettel-cdn.vn/bangtin/180a60b7-2026-4341-b053-eb2b59a40b74_small.jpg
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://doanhnhansaigon.vn
    minimum_topic_length: 4
    browser_timeout: 60
    prevent_auto_redirect: false
