- Pháp Luật Việt Nam:
    id_type: href
    browser_profile: ''
    web_url: http://baophapluat.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths:
    - //node()[@class='article__tag']
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - (//node()[@class='content'])[2]//img/@src
    - (//node()[@class='content'])[2]//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //node()[@class='article__summary cms-desc']/div/text()
    - //node()[@class='article__summary cms-desc']/div/text()
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: http://baophapluat.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //node()[@class='article__meta']/time
    - //node()[@class='article__meta']/time
    topic_type: href
    maximum_url: 30
    get_detail_content: true
    content_xpath:
    - (//node()[@class='content'])[2]
    - (//node()[@class='content'])[2]
    text_xpath:
    - (//node()[@class='content'])[2]/node()[@class='cms-body']/p
    image_box_xpath:
    - (//node()[@class='content'])[2]/node()[@class='full-img']
    image_title_xpath:
    - (//node()[@class='content'])[2]/node()[@class='full-img']/node()[@class='fig']
    - (//node()[@class='content'])[2]/div[@class='full-img']/span[@class='fig']
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: ''
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: http://baophapluat.vn
    minimum_topic_length: 4
    browser_timeout: 60
    prevent_auto_redirect: false
