- Báo  Cao Bằng điện tử:
    id_type: href
    browser_profile: ''
    web_url: http://baocaobang.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths: []
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - //node()[@class='text']//img/@src
    - //node()[@class='text']//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - (//node()[@class='sapo']//text()/..)[last()]/text()
    - (//node()[@class='sapo']//text()/..)[last()]/text()
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: http://baocaobang.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //node()[@class='time']
    - //node()[@class='time']
    topic_type: href
    maximum_url: 30
    get_detail_content: true
    content_xpath:
    - //node()[@class='text']
    - //node()[@class='text']
    text_xpath:
    - //node()[@class='text']/p
    - //node()[@class='text']/div/p
    image_box_xpath:
    - //node()[@class='picBox']
    - //node()[@align='center']//img/ancestor::table
    image_title_xpath:
    - //node()[@class='picBox']/tbody/tr[2]/td//text()/..
    - //node()[@align='center']//img/ancestor::table/tbody/tr[2]/td//text()/..
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: http://img.baocaobang.epi.vn/zoom/1000_131/uploaded/2019/zugtnw/2018_02_06/b3_jniw.jpg
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: http://baocaobang.vn
    minimum_topic_length: 4
    browser_timeout: 60
    prevent_auto_redirect: false
