- VTC:
    id_type: href
    browser_profile: ''
    web_url: https://vtc.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths:
    - //node()[@class='single-tags']
    - //node()[@class='block_with_img_left']
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - //node()[@class='single-main-content']//img/@src
    - //node()[@class='single-main-content']//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //node()[@class='single-excerpt']/strong/text()
    - //node()[@class='single-excerpt']/strong/text()
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: https://vtc.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //node()[@pubdate='pubdate']
    - //node()[@pubdate='pubdate']
    topic_type: href
    maximum_url: 60
    get_detail_content: true
    content_xpath:
    - //node()[@class='single-main-content']
    - //node()[@class='single-main-content']
    text_xpath:
    - //node()[@class='single-main-content']/p
    - '//node()[@style=''text-transform: uppercase; color: #a3171e;font-weight:700;float:right'']'
    image_box_xpath:
    - //node()[@class='expNoEdit']
    image_title_xpath:
    - //figcaption/p/em
    - //figcaption/p
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: http://ainewsobj.6112cf5e.viettel-cdn.vn/bangtin/8da6e7d2-e456-47fb-8315-af9127d02e06_small.jpg
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://vtc.vn
    minimum_topic_length: 4
    browser_timeout: '120'
    prevent_auto_redirect: false
