- Báo điện tử Hải Phòng:
    id_type: href
    browser_profile: ''
    web_url: http://www.baohaiphong.com.vn/baohp/vn/home/
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths:
    - //node()[@class='row1 creatdate' or @class='title' or @class='stitle' or @class='row1'
      or @class='head']
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - //node()[@id='newsContent']//img/@src
    - //node()[@id='newsContent']//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //node()[@class='head']//text()
    - //node()[@class='head']//text()
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: true
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: http://www.baohaiphong.com.vn/baohp/vn/home/
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //node()[@class='row1 creatdate']
    - //node()[@class='row1 creatdate']
    topic_type: href
    maximum_url: 10
    get_detail_content: true
    content_xpath:
    - //node()[@id='newsContent']
    - //node()[@id='newsContent']
    text_xpath:
    - //node()[@id='newsContent']/p[not(img)]
    - //node()[@id='newsContent']/b
    image_box_xpath:
    - //node()[@class='picBox']
    - //node()[@id='newsContent']/p/img/..
    image_title_xpath:
    - //node()[@class='picBox']/tbody/tr[2]/td//text()/..
    - //node()[@id='newsContent']/p/img/../following-sibling::p[@align='center']//text()/..
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: http://www.baohaiphong.com.vn/baohp/vn/upload/bann/image/1563965027912_Untitled22.jpg
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: http://www.baohaiphong.com.vn
    minimum_topic_length: 4
    browser_timeout: 120
    prevent_auto_redirect: false
