- Bizlive:
    id_type: href
    browser_profile: ''
    web_url: https://bizlive.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: true
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths:
    - //div[@class="related-news"]
    - //div[@class="simplebanner banner qc"]
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - //div[@class="full-img"]
    - //div[@class="full-img"]
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //div[@class="sapo"]
    - //div[@class="sapo"]
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: https://bizlive.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //time
    - //time
    topic_type: href
    maximum_url: 30
    get_detail_content: true
    content_xpath:
    - //div[@class="main-content"]
    - //div[@class="main-content"]
    text_xpath:
    - //div[@class="main-content"]/div[@id="abody"]//*[./text()]
    image_box_xpath:
    - //div[@class="main-content"]/div[@id="abody"]//div[./img]
    image_title_xpath: []
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: ''
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://bizlive.vn
    minimum_topic_length: 4
    tags: []
    only_quality_post: true
    browser_timeout: 60
    prevent_auto_redirect: false
