- CafeF:
    id_type: href
    browser_profile: ''
    web_url: http://cafef.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths: []
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - //div[@class="left_cate totalcontentdetail"]//img/@src
    - //div[@class="left_cate totalcontentdetail"]//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //node()[@class='sapo']/text()
    - //node()[@class='sapo']/text()
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: http://cafef.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //span[@class='pdate']
    - //span[@class='pdate']
    topic_type: href
    maximum_url: 30
    get_detail_content: true
    content_xpath:
    - //node()[@class="w640 fr clear"]
    - //node()[@class="w640 fr clear"]
    text_xpath:
    - ./node()[@id="contentdetail"]/node()[@id="mainContent"]/p
    image_box_xpath:
    - .//div[@class="media"]
    - ./node()[@id="contentdetail"]/node()[@id="mainContent"]/div[@type="Photo"]
    image_title_xpath:
    - .//div[@class="PhotoCMS_Caption"]/p
    - ./div[@class="avatar-des"]
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: ''
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: http://cafef.vn
    minimum_topic_length: 4
    tags: []
    only_quality_post: true
    browser_timeout: 60
    prevent_auto_redirect: false
