- Công Thương:
    id_type: href
    browser_profile: ''
    web_url: https://congthuong.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths: []
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - .//img/@src
    - .//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //div[@class='article-desc fw lt clearfix']/text()
    - //div[@class='article-desc fw lt clearfix']/text()
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: true
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: https://congthuong.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //span[@class='bx-time lt']
    - //span[@class='bx-time lt']
    topic_type: href
    maximum_url: 10
    get_detail_content: true
    content_xpath:
    - //div[@class='__MASTERCMS_CONTENT __MB_CONTENT_FOR_PRINTER fw lt mb-15 clearfix']
    - //div[@class='__MASTERCMS_CONTENT __MB_CONTENT_FOR_PRINTER fw lt mb-15 clearfix']
    text_xpath:
    - ".//p[text()]\t"
    image_box_xpath:
    - .//tbody[descendant::img]
    image_title_xpath:
    - .//tr[2]/td
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: http://ainewsobj.6112cf5e.viettel-cdn.vn/bangtin/9cd5ce3e-3041-41d0-ab2a-b6d41be2512d_small.jpg
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://congthuong.vn
    minimum_topic_length: 4
