- Dân Trí:
    web_url: https://dantri.com.vn
    crawl_url: https://dantri.com.vn
    language: vietnamese
    id_type: href
    url_pattern_re: (http|https)://dantri.com.vn
    get_topic_from_link: true
    topics_xpath:
    - //a[contains(@href, 'htm') and @data-id]
    - //a[contains(@href, 'htm') and child::b]
    topic_type: href
    extract_xpath:
    - ./@title()
    - ./@title()
    contain: ''
    minimum_topic_length: 4
    skip_checking_topic_length: false
    get_publish_date_as_crawl_date: false
    date_place: detail_page
    date_xpath:
    - //span[@class='fr fon7 mr2 tt-capitalize']
    use_index_number: false
    date_re:
    - (\d{1,2}[\/\-\.]\d{1,2}[\/\-\.]\d{2,4} - \d{1,2}:\d{1,2})
    date_pattern:
    - '%d/%m/%Y - %H:%M'
    timezone: Asia/Ho_Chi_Minh
    output_html: false
    use_browser: true
    browser_profile: ''
    display_browser: false
    browser_fast_load: true
    maximum_url: 10
    last_run: 02/06/2019 21:56
    minimum_duration_between_crawls: 15
