- Đấu Thầu:
    id_type: href
    browser_profile: ''
    web_url: https://baodauthau.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths:
    - //div[@class='clearfix' or @class='article-tag clearfix' or class='social-share
      clearfix' or @class='comment-zone clearfix']
    - //div[@class='quote pull-right cms-quote']
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - .//img/@src
    - .//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //div[@class='sapo cms-desc']
    - //div[@class='sapo cms-desc']
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: https://baodauthau.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //time[parent::div[@class='meta clearfix']]
    - //time[parent::div[@class='meta clearfix']]
    topic_type: href
    maximum_url: 10
    get_detail_content: true
    content_xpath:
    - //article[child::div[@class='content cms-body']]
    - //article[child::div[@class='content cms-body']]
    text_xpath:
    - ".//p[text()]\t"
    image_box_xpath:
    - .//div[@class='full-img cms-body']
    image_title_xpath:
    - //div[@class='fig']
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: http://ainewsobj.6112cf5e.viettel-cdn.vn/bangtin/7b0ec8dc-0505-4642-950b-2766a8961f85_small.jpg
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://baodauthau.vn
    minimum_topic_length: 4
