- diễn đàn doanh nghiệp Việt Nam:
    id_type: href
    browser_profile: ''
    web_url: https://enternews.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths:
    - //node()[@class='fa fa-clock-o' or @class='cl']
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - ''
    - ''
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //h2[@class='post-sapo']/strong/text()
    - //h2[@class='post-sapo']/strong/text()
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: true
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: https://enternews.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //div[@class='pull-right mt-5 mr-10']
    - //div[@class='pull-right mt-5 mr-10']
    topic_type: href
    maximum_url: 10
    get_detail_content: true
    content_xpath:
    - //div[@class='cols-xs-9 w-833']
    - //div[@class='cols-xs-9 w-833']
    text_xpath:
    - .//h1[text()]
    - .//p[text()]
    image_box_xpath:
    - //div[@class='image_center_wp']
    image_title_xpath:
    - //p[@class='image_caption']/text()
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: https://m.enternews.vn/themes/mobile/images/logo.png
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://enternews.vn
    minimum_topic_length: 4
