- Đời Sống Pháp Luật:
    web_url: https://www.doisongphapluat.com
    crawl_url: https://www.doisongphapluat.com
    url_pattern_re: (http|https)://www.doisongphapluat.com
    language: vietnamese
    get_topic_from_link: true
    id_type: href
    topic_type: text
    topics_xpath:
    - //node()[@class='heading' or @class='title' or @class='sub-title']/a[string-length(text())>20]
    extract_xpath:
    - ./text()
    contain: ''
    minimum_topic_length: 4
    skip_checking_topic_length: false
    get_publish_date_as_crawl_date: false
    date_place: detail_page
    date_xpath:
    - //node()[@class='fl-right dt']
    use_index_number: false
    date_re: (\d{1,2}[\/\-\.]\d{1,2}[\/\-\.]\d{2,4} \| \d{1,2}:\d{1,2})
    date_pattern: '%d/%m/%Y | %H:%M'
    timezone: Asia/Ho_Chi_Minh
    output_html: false
    use_browser: true
    display_browser: false
    browser_fast_load: false
    maximum_url: 10
    last_run: 05/06/2019 11:03
    minimum_duration_between_crawls: 10
