- danghailochp:
    web_url: https://www.facebook.com/danghailochp
    crawl_url: https://www.facebook.com/danghailochp
    crawl_type: facebook user
    language: vietnamese
    url_pattern_re: https://www.facebook.com/danghailochp
    contain: ''
    minimum_topic_length: 4
    skip_checking_topic_length: true
    get_publish_date_as_crawl_date: false
    output_html: false
    use_browser: true
    browser_profile: test_profile
    display_browser: false
    browser_fast_load: true
    maximum_url: 5
    last_run: 28/05/2019 23:41
    minimum_duration_between_crawls: 5
