- Gia Đình Việt Nam:
    id_type: href
    browser_profile: ''
    web_url: https://giadinhvietnam.com
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths:
    - //p[descendant::a[@target='_blank']]
    - //p[descendant::iframe[@class='exp_video']]
    - //node()[@class='w100 fl bor_suggest']
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - .//img/@src
    - .//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //node()[@class='w100 intro_detail fl']/text()
    - //node()[@class='w100 intro_detail fl']/text()
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: https://giadinhvietnam.com
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //span[@class='date_title_hot']
    - //span[@class='date_title_hot']
    topic_type: href
    maximum_url: 30
    get_detail_content: true
    content_xpath:
    - //node()[@id='content_detail']
    - //node()[@id='content_detail']
    text_xpath:
    - .//p[text()]
    - .//h2/strong/em[text()]
    image_box_xpath:
    - .//figure[@class='expNoEdit']
    image_title_xpath:
    - './following-sibling::p[@style=''text-align: center;'']//strong[text()]'
    - './following-sibling::p[@style=''text-align: center;'']//em[text()]'
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: http://ainewsobj.6112cf5e.viettel-cdn.vn/bangtin/b8b39586-995c-4323-a404-a3d8aa06c863_small.jpg
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://giadinhvietnam.com
    minimum_topic_length: 4
    browser_timeout: 60
    prevent_auto_redirect: false
