- Giáo Dục Việt Nam:
    id_type: href
    browser_profile: ''
    web_url: https://giaoduc.net.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: true
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths:
    - //table[@class='notebox cms-relate nright']
    - //table[@class='notebox cms-relate nleft']
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - .//img[ancestor::table[@class='picture']]/@src
    - .//img[ancestor::table[@class='picture']]/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //node()[@class='details__summary cms-desc']/text()
    - //node()[@class='details__summary cms-desc']/text()
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: https://giaoduc.net.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //time[@class='cms-date']
    - //time[@class='cms-date']
    topic_type: href
    maximum_url: 10
    get_detail_content: true
    content_xpath:
    - //node()[@class='details__content cms-body']
    - //node()[@class='details__content cms-body']
    text_xpath:
    - .//p[text()]
    image_box_xpath:
    - .//td[@class='pic']
    image_title_xpath:
    - ./following::td[@class='caption']//em[text()]
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: http://ainewsobj.6112cf5e.viettel-cdn.vn/bangtin/b2d4e9ca-eacc-4f26-a480-ee0979724c09_small.jpg
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://giaoduc.net.vn
    minimum_topic_length: 4
    browser_timeout: 60
    prevent_auto_redirect: false
