- Giáo Dục & Thời Đại:
    id_type: href
    browser_profile: ''
    web_url: https://giaoducthoidai.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths: ''
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - .//img/@src
    - .//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //node()[@class='summary cms-desc']
    - //node()[@class='summary cms-desc']
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: https://giaoducthoidai.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //div[@class='toolbar clearfix']/span[@class='time']
    - //div[@class='toolbar clearfix']/span[@class='time']
    topic_type: href
    maximum_url: 10
    get_detail_content: true
    content_xpath:
    - //div[@id="articlecontent"]
    - //div[@id="articlecontent"]
    text_xpath:
    - .//p[not(contains(@class, "avatar"))]//text()/..
    image_box_xpath:
    - ./div//p[@class="avatar"]
    - .//table/tbody
    - ./div/div/div/img/..
    image_title_xpath:
    - .//span
    - ./tr[2]/td//em
    - .
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: http://ainewsobj.6112cf5e.viettel-cdn.vn/bangtin/5cc1a10b-0dfc-4a96-9a7b-19e8eff2232c_small.jpg
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://giaoducthoidai.vn
    minimum_topic_length: 4
    only_quality_post: true
    tags: []
    browser_timeout: 60
    prevent_auto_redirect: false
