- Golf and life:
    id_type: href
    browser_profile: ''
    web_url: https://golfandlife.com.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths:
    - //div[@class="hatom-extra"]
    - //div[@class="post-tags"]
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - //div[@class="inner-post-entry"]//img/@src
    - //div[@class="inner-post-entry"]//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - ''
    - ''
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: https://golfandlife.com.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //div[@class="post-box-meta-single"]/span[2]/text()
    - //div[@class="post-box-meta-single"]/span[2]/text()
    topic_type: href
    maximum_url: 10
    get_detail_content: true
    content_xpath:
    - //div[@class="inner-post-entry"]
    - //div[@class="inner-post-entry"]
    text_xpath:
    - //div[@class="inner-post-entry"]/p[not(.//img)]
    image_box_xpath:
    - //div[@class="inner-post-entry"]/*[.//img]
    image_title_xpath: []
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: xpath
    avatar_url: ''
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://golfandlife.com.vn
    minimum_topic_length: 4
    tags: []
