- Kênh 14:
    web_url: http://kenh14.vn
    crawl_url: http://kenh14.vn
    language: vietnamese
    id_type: href
    url_pattern_re: (http|https)://kenh14.vn
    get_topic_from_link: true
    topics_xpath:
    - //a[contains(@href, 'chn') and string-length(text())>20]
    topic_type: href
    extract_xpath:
    - ./text()
    contain: ''
    minimum_topic_length: 4
    skip_repeat_topic: false 
    skip_checking_topic_length: false
    get_publish_date_as_crawl_date: false
    date_place: detail_page
    date_xpath:
    - //node()[@class='kbwcm-time' or @class='afcbat-data']
    use_index_number: false
    date_re:
    - (\d{2,4}[\/\-\.]\d{1,2}[\/\-\.]\d{1,2}T\d{1,2}:\d{1,2})
    date_pattern:
    - '%Y-%m-%dT%H:%M'
    timezone: Asia/Ho_Chi_Minh
    output_html: false
    use_browser: true
    browser_profile: ''
    display_browser: false 
    browser_fast_load: false
    maximum_url: 10
    last_run: 02/06/2019 21:56
    minimum_duration_between_crawls: 10
