- Quân khu 7:
    id_type: href
    browser_profile: ''
    web_url: http://baoquankhu7.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths:
    - //node()[@class='tintuc-lienquan']
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - ./img/@src
    - ./img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //h2[@class='title-content-tin']/text()
    - //h2[@class='title-content-tin']/text()
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: true
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: http://baoquankhu7.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //div[@class='date']
    - //div[@class='date']
    topic_type: href
    maximum_url: 10
    get_detail_content: true
    content_xpath:
    - //div[@class='content-tin']
    - //div[@class='content-tin']
    text_xpath:
    - .//span[text()]
    image_box_xpath:
    - //div[@class='text-align:center;']
    image_title_xpath: []
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: http://www.baoquankhu7.vn/Areas/ExtAppCommon/Content/QUAN-KHU-7/img/logo.png
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: http://baoquankhu7.vn
    minimum_topic_length: 4
