- Du Lịch:
    id_type: href
    browser_profile: ''
    web_url: http://tapchidulich.net.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths:
    - //node()[@class='news-detail-content']//table
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - .//img/@src
    - .//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //div[@class='news-detail-mota']/*/text()
    - //div[@class='news-detail-mota']/*/text()
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: http://tapchidulich.net.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //node()[@class='news-detail-date']
    - //node()[@class='news-detail-date']
    topic_type: href
    maximum_url: 10
    get_detail_content: true
    content_xpath:
    - //node()[@class='news-detail-content']
    - //node()[@class='news-detail-content']
    text_xpath:
    - .//p[text()]
    image_box_xpath:
    - .//p[descendant::img]
    image_title_xpath:
    - .//img/following-sibling::div[@class='alt']
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: http://ainewsobj.6112cf5e.viettel-cdn.vn/bangtin/8b5fa5c9-f382-4498-afcf-27085a8892e4_small.jpg
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: http://tapchidulich.net.vn
    minimum_topic_length: 4
