- Sức Khỏe & Môi Trường:
    id_type: href
    browser_profile: ''
    web_url: http://suckhoemoitruong.com.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths: []
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - .//img/@src
    - .//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //div[@class='clearfix mgb20']//p[descendant::strong][1]//span/text()
    - //div[@class='clearfix mgb20']//p[descendant::strong][1]//span/text()
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: http://suckhoemoitruong.com.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //li[@class='time']
    - //li[@class='time']
    topic_type: href
    maximum_url: 30
    get_detail_content: true
    content_xpath:
    - //div[@class='clearfix mgb20']
    - //div[@class='clearfix mgb20']
    text_xpath:
    - .//span[not (descendant::img)][text()]
    image_box_xpath:
    - .//p[descendant::img]
    image_title_xpath:
    - ./following-sibling::p[descendant::em][contains(@style, 'text-align:center')]//span[text()]
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: http://ainewsobj.6112cf5e.viettel-cdn.vn/bangtin/07feb9de-8b8b-4901-a44b-cb8887a39f7e_small.jpg
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: http://suckhoemoitruong.com.vn
    minimum_topic_length: 4
    browser_timeout: 60
    prevent_auto_redirect: false
