- Tạp chí Sở hữu trí tuệ và Sáng tạo:
    id_type: href
    browser_profile: ''
    web_url: https://sohuutritue.net.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths: []
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - .//img/@src
    - .//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //node()[@class='intro']/text()
    - //node()[@class='intro']/text()
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: https://sohuutritue.net.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //time[@class='pushdate']
    - //time[@class='pushdate']
    topic_type: href
    maximum_url: 30
    get_detail_content: true
    content_xpath:
    - //div[@class='content-detail']
    - //div[@class='content-detail']
    text_xpath:
    - .//p[text()]
    - .//p//strong[text()]
    image_box_xpath:
    - .//figure[descendant::img]
    image_title_xpath:
    - ./figcaption//strong[text()]
    - ./figcaption//em[text()]
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: https://sohuutritue.net.vn/templates/themes/images/logo.png
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://sohuutritue.net.vn
    minimum_topic_length: 4
    browser_timeout: 60
    prevent_auto_redirect: false
