- Techz:
    id_type: href
    browser_profile: ''
    web_url: https://www.techz.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: true
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths:
    - //div[@class="news-relation-top-detail"]
    - //div[@class="news-other"]
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - .//img/@src
    - .//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //div[@class="sapo-detail"]//h2/text()
    - //div[@class="sapo-detail"]//h2/text()
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: https://www.techz.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //node()[@class="post-time"]
    - //node()[@class="post-time"]
    topic_type: href
    maximum_url: 50
    get_detail_content: true
    content_xpath:
    - //div[@itemprop="articleBody"]
    - //div[@itemprop="articleBody"]
    text_xpath:
    - './/p[@style="text-align: justify;"][text()]'
    - './/p[@style="text-align: justify;"]//span[text()]'
    image_box_xpath:
    - .//figure[@class="image align-center"]
    - .//p[descendant::img]
    image_title_xpath:
    - ./figcaption[text()]
    - './following-sibling::p[@style="text-align: center;"]//em//span[text()]'
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: ''
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://www.techz.vn
    minimum_topic_length: 4
    tags: []
    only_quality_post: true
    browser_timeout: 60
    prevent_auto_redirect: false
