- Thời Báo Tài Chính Việt Nam:
    id_type: href
    browser_profile: ''
    web_url: http://thoibaotaichinhvietnam.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths:
    - //node()[@id='ctl00_PlaceHolderMain_g_d88e36f0_76e7_4d47_8fab_9aead874db20']
    - //node()[@class='article-content article-content02']/div/strong
    - //node()[@class='article-ds']//table[@border='0']
    - //node()[@class='article-ds']//table[@border='2']
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - //node()[@class='article-ds']//img/@src
    - //node()[@class='article-ds']//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //node()[@id='ctl00_PlaceHolderMain_g_d88e36f0_76e7_4d47_8fab_9aead874db20']/text()
    - //node()[@id='ctl00_PlaceHolderMain_g_d88e36f0_76e7_4d47_8fab_9aead874db20']/text()
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: http://thoibaotaichinhvietnam.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //node()[@class='date-time dtngaydang']
    - //node()[@class='date-time dtngaydang']
    topic_type: href
    maximum_url: 30
    get_detail_content: true
    content_xpath:
    - //node()[@class='article-ds']
    - //node()[@class='article-ds']
    text_xpath:
    - //node()[@class='article-ds']/div/div/p
    - //node()[@class='tacgia']
    image_box_xpath:
    - //node()[@class='main-showeditdetail']
    - //node()[@class='article-ds']//table[@align='right']
    - //node()[@class='article-ds']//table
    image_title_xpath:
    - //node()[@class='article-ds']//table/tbody/tr[2]/td/p/em/span
    - //node()[@class='img-caption']
    - //node()[@style='font-size:12px;']
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: http://ainewsobj.6112cf5e.viettel-cdn.vn/bangtin/c54f9774-df21-4c18-a60a-e566d944439e_small.jpg
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: http://thoibaotaichinhvietnam.vn
    minimum_topic_length: 4
    browser_timeout: 60
    prevent_auto_redirect: false
