- Tin Tức:
    id_type: href
    browser_profile: ''
    web_url: https://baotintuc.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths:
    - node()[@class='breadcrumb' or @class='sharefb']
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - .//img/@src
    - .//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //h2[@class='sapo w670']/text()
    - //h2[@class='sapo w670']/text()
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: https://baotintuc.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //div[@class='time']
    - //div[@class='time']
    topic_type: href
    maximum_url: 10
    get_detail_content: true
    content_xpath:
    - //div[@class='mixcontent ']
    - //div[@class='mixcontent']
    text_xpath:
    - .//p[text()]
    image_box_xpath:
    - //figure[@class='image']
    image_title_xpath:
    - //figcaption
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: http://ainewsobj.6112cf5e.viettel-cdn.vn/bangtin/81d9e1c6-51e1-427d-87d3-31c8d9b0543a_small.jpg
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://baotintuc.vn
    minimum_topic_length: 4
    only_quality_post: true
    tags: []
    browser_timeout: 60
    prevent_auto_redirect: false
