- Tuổi Trẻ Thủ Đô:
    id_type: href
    browser_profile: ''
    web_url: https://tuoitrethudo.com.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: true
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths:
    - //node()[@class='tit-arrticle']
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - .//img/@src
    - .//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //div[@class='title-article-content']/h3/text()
    - //div[@class='title-article-content']/h3/text()
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: https://tuoitrethudo.com.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //div[@class='cate-date']
    - //div[@class='cate-date']
    topic_type: href
    maximum_url: 70
    get_detail_content: true
    content_xpath:
    - //div[@class='article-check']
    - //div[@class='article-check']
    text_xpath:
    - //node()[@id="content_detail"]/p
    image_box_xpath:
    - //div[@class='content-article-top-img']
    - //figure[@class='expNoEdit']
    image_title_xpath:
    - './/figcaption[@style=''width: 668px;]/h2'
    - //p[@class='image_intro']
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: ''
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://tuoitrethudo.com.vn
    minimum_topic_length: 4
    tags: []
    browser_timeout: 60
    prevent_auto_redirect: false
