- VOV:
    crawl_url: https://vov.vn
    timezone: Asia/Ho_Chi_Minh
    browser_fast_load: true
    contain: ''
    date_place: detail_page
    image_title_xpath:
    - .//tr[2]/td//node()[text()]
    - .//div[text()]
    get_topic_from_link: true
    video_title_text_xpath: ''
    topic_type: href
    audio_box_xpath: []
    language: vietnamese
    skip_checking_topic_length: false
    remove_date_tag_html: false
    remove_content_html_xpaths:
    - //node()[@class='sapo' or @class='relate-container' or contains(@class, 'VCSortableInPreviewMode')]
    skip_repeat_topic: true
    extract_xpath:
    - ./text()
    - ./@title
    image_box_xpath:
    - .//table[@class='contentimg']
    - .//div[@class='item contentimg']
    date_xpath:
    - //node()[@class="article__meta"]
    - //node()[@class="article__meta"]
    remove_content_html: true
    minimum_topic_length: 4
    avatar_url: http://ainewsobj.6112cf5e.viettel-cdn.vn/bangtin/a1e35547-1fd4-4331-aea0-fd1bc355635b_small.jpg
    image_title_text_xpath: ''
    last_run: 22/07/2019 04:02
    audio_title_text: ''
    crawl_type: newspaper
    display_browser: false
    maximum_url: 10
    output_html: false
    text_xpath:
    - .//p[text()]
    get_detail_content: true
    use_browser: false
    get_publish_date_as_crawl_date: false
    avatar_type: url
    image_xpath: ''
    use_index_number: false
    feature_image_xpath:
    - .//img/@src
    - .//img/@src
    topics_xpath:
    - //a[text()]
    - //a[@title]
    content_xpath:
    - //div[@class='text main-contents article__body']
    - //div[@class='text main-contents article__body']
    video_box_xpath: []
    id_type: href
    video_title_xpath: []
    avatar_xpath: ''
    ignore_topic_not_have_publish_date: true
    audio_title_xpath: []
    url_pattern_re: https://vov.vn
    minimum_duration_between_crawls: -5
    sapo_xpath:
    - //div[@class='article__sapo']
    - //div[@class='article__sapo']
    browser_profile: ''
    web_url: https://vov.vn
