// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1578994681);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1578994711);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 14966);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1578994651);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 89);
user_pref("browser.newtabpage.activity-stream.impressionId", "{d6e8d3b0-ef0f-4efb-b62c-f24185a4404c}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1578994664774");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1578996454774");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1578994655220");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1578998255220");
user_pref("browser.search.region", "VN");
user_pref("browser.slowStartup.averageTime", 25975);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200107212822");
user_pref("browser.startup.homepage_override.mstone", "72.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1578994652);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1578994653787");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "72.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "a6f7e17427ff41beb6768102df7771dd");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "72.0.1");
user_pref("extensions.lastPlatformVersion", "72.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"53aca231-5b1f-4550-9719-f84be9e09b61\",\"formautofill@mozilla.org\":\"d9c0c82b-5f13-4bfd-a16c-f628516b3124\",\"screenshots@mozilla.org\":\"331d1ca6-b62e-4d58-bfb9-6403fe5dd0e2\",\"webcompat-reporter@mozilla.org\":\"c765791c-205f-4c3d-9019-95063356498f\",\"webcompat@mozilla.org\":\"5aa88678-d4cd-4ea7-9d80-f89e9e5ed08e\",\"default-theme@mozilla.org\":\"30bc8f7e-48e7-4b95-a9df-68589f5aa55b\",\"google@search.mozilla.org\":\"303222f7-18a2-49cc-a1cd-c830a4f35ddd\",\"amazondotcom@search.mozilla.org\":\"ada97965-c602-44d3-aea5-958be72ea7ee\",\"bing@search.mozilla.org\":\"34ce0705-dd81-4002-bfcd-0ec6eb35e18f\",\"ddg@search.mozilla.org\":\"b671a933-2931-40f0-b9da-555bb29edf5e\",\"ebay@search.mozilla.org\":\"28ea2681-c304-4b60-b2a8-93bf922ebab4\",\"twitter@search.mozilla.org\":\"efdaf087-613c-49b6-ad47-4631469f9565\",\"wikipedia@search.mozilla.org\":\"127396fa-75db-43e5-8305-100ea50cf8a2\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("permissions.eventTelemetry.salt", "{b999154c-3f48-4462-8974-216cfc42b82f}");
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "4028f7f4-8b40-4ed6-bc76-126539c7ea9e");
user_pref("security.sandbox.plugin.tempDirSuffix", "76d9b540-34ee-48fe-889d-35e2610efc33");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1578994650);
user_pref("toolkit.telemetry.cachedClientID", "c45dfd0c-bf23-49f4-9df5-37d7bb605c5a");
user_pref("toolkit.telemetry.previousBuildID", "20200107212822");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
