// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1578993769);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1578993799);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 9893);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1578993739);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 89);
user_pref("browser.newtabpage.activity-stream.impressionId", "{4e3db4d2-7384-4ef9-9454-5ed6e3c1bbc9}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1578993779067");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1578995597067");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1578993743327");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1578997343327");
user_pref("browser.search.region", "VN");
user_pref("browser.slowStartup.averageTime", 35635);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200107212822");
user_pref("browser.startup.homepage_override.mstone", "72.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1578993740);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1578993741862");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "72.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "751ff4852efc46e3940cf2603a73899c");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "72.0.1");
user_pref("extensions.lastPlatformVersion", "72.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"7f616c08-b2a6-41f0-a4dd-51dd3035ba40\",\"formautofill@mozilla.org\":\"4e6153f8-9db5-46b6-bb36-d77760e4ca8b\",\"screenshots@mozilla.org\":\"abe5872c-2be0-47dd-b69c-09e934dde13b\",\"webcompat-reporter@mozilla.org\":\"78b30db5-f85d-4da2-806b-042fae347002\",\"webcompat@mozilla.org\":\"760c3d0f-9272-4485-a354-586d0add3904\",\"default-theme@mozilla.org\":\"621e96a4-7f46-4f49-bdee-89eef8831ea9\",\"google@search.mozilla.org\":\"dc52db19-2dc8-4271-81e4-375be15445e9\",\"amazondotcom@search.mozilla.org\":\"690a14ca-4155-4eea-a9fa-494772a1bd83\",\"bing@search.mozilla.org\":\"9b362f8f-6031-4d2a-92ed-143a5760e798\",\"ddg@search.mozilla.org\":\"21797221-ae00-4fd6-a655-ad980964ee2f\",\"ebay@search.mozilla.org\":\"daaa6868-8003-494f-940e-0285fdce1e5b\",\"twitter@search.mozilla.org\":\"41e30f55-ade5-49be-aeca-e4f87a994e13\",\"wikipedia@search.mozilla.org\":\"eb7ae725-9eb8-4a10-98bd-a4bcd1d745dd\"}");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1578993770);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20200107212822");
user_pref("media.gmp-manager.lastCheck", 1578993769);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("permissions.eventTelemetry.salt", "{fd72e184-cce8-46ec-9332-140efeabd9bd}");
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "ae27f589-32d6-47d4-9092-f41c3d9e0d3f");
user_pref("security.sandbox.plugin.tempDirSuffix", "23ca908f-8550-4dca-b066-af51dea16adf");
user_pref("services.blocklist.pinning.checked", 1578993777);
user_pref("services.settings.clock_skew_seconds", -8);
user_pref("services.settings.last_etag", "\"1578960089219\"");
user_pref("services.settings.last_update_seconds", 1578993777);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1578993777);
user_pref("services.settings.main.cfr-fxa.last_check", 1578993777);
user_pref("services.settings.main.cfr.last_check", 1578993777);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1578993777);
user_pref("services.settings.main.hijack-blocklists.last_check", 1578993777);
user_pref("services.settings.main.language-dictionaries.last_check", 1578993777);
user_pref("services.settings.main.public-suffix-list.last_check", 1578993777);
user_pref("services.settings.main.sites-classification.last_check", 1578993777);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1578993777);
user_pref("services.settings.main.whats-new-panel.last_check", 1578993777);
user_pref("services.settings.security.onecrl.checked", 1578993777);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1578993738);
user_pref("toolkit.telemetry.cachedClientID", "db7cc972-1dc7-4e41-8c69-b78998ca18bb");
user_pref("toolkit.telemetry.previousBuildID", "20200107212822");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
