// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.normandy.user_id", "94108a8c-8d74-4d89-a4b9-6ac0a6f51799");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1578994409);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1578994439);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 12539);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1578994378);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 89);
user_pref("browser.newtabpage.activity-stream.impressionId", "{6313e938-35da-4a68-abcd-5924e8b89f3f}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1578994411448");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1578996217448");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1578994383133");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1578997983133");
user_pref("browser.search.region", "VN");
user_pref("browser.slowStartup.averageTime", 41877);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200107212822");
user_pref("browser.startup.homepage_override.mstone", "72.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1578994380);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1578994381717");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "72.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "f717311b5e9a421798736ba3033716ed");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "72.0.1");
user_pref("extensions.lastPlatformVersion", "72.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"1ed479f3-c9b7-4104-a550-2e8b1d84b677\",\"formautofill@mozilla.org\":\"86446ece-c899-4634-9455-4abc3f3d14a2\",\"screenshots@mozilla.org\":\"6acdd670-a0e0-4315-a933-b7d5b7092749\",\"webcompat-reporter@mozilla.org\":\"7a83f92a-3f36-49c1-a25e-efd8cf80fb01\",\"webcompat@mozilla.org\":\"5bf6505e-8b20-4108-8cca-b27d53c9e3dd\",\"default-theme@mozilla.org\":\"7033c538-2f66-4434-b3c1-6d355384090d\",\"google@search.mozilla.org\":\"9b810c20-a230-4b00-b249-6c2ebe87b798\",\"amazondotcom@search.mozilla.org\":\"b3adacdf-b48d-485a-9171-245c897bf9d5\",\"bing@search.mozilla.org\":\"ab6a9dc0-ab12-473c-a95b-eed6108717ca\",\"ddg@search.mozilla.org\":\"a408673e-0b52-4f38-8d74-5ff65562407d\",\"ebay@search.mozilla.org\":\"900fb250-f488-4e59-ad6a-67c16b2ddf5e\",\"twitter@search.mozilla.org\":\"2bfeb255-40b8-454a-95bb-b924d1f112c3\",\"wikipedia@search.mozilla.org\":\"a4383194-9df3-48f1-95c4-08951ed77b96\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("permissions.eventTelemetry.salt", "{b61a95f1-cb99-459d-8a55-ee68fd310bf0}");
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "a109322e-1123-455c-8d64-142ba8ff30fe");
user_pref("security.sandbox.plugin.tempDirSuffix", "d2a9e368-597c-4df0-9794-12e9aa810c73");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1578994377);
user_pref("toolkit.telemetry.cachedClientID", "28535235-9e05-4dbd-bd3f-5d38b3e01843");
user_pref("toolkit.telemetry.previousBuildID", "20200107212822");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
