// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1578994114);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1578994234);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1578994144);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 47899);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1578994084);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 89);
user_pref("browser.newtabpage.activity-stream.impressionId", "{27b83654-71b0-4c14-9f44-9170cbf382a4}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1578994108880");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1578995911880");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1578994088568");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1578997688568");
user_pref("browser.search.region", "VN");
user_pref("browser.slowStartup.averageTime", 24587);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200107212822");
user_pref("browser.startup.homepage_override.mstone", "72.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1578994085);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1578994086793");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "72.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "1d2ec99777f5454c90d086e06fd61223");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "72.0.1");
user_pref("extensions.lastPlatformVersion", "72.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"6c9664a3-ca76-4d4c-8c78-64dd55ce3d03\",\"formautofill@mozilla.org\":\"10a03d81-6908-4ef5-9406-c21c1def4ce1\",\"screenshots@mozilla.org\":\"e9656bbf-72b7-4a89-90d7-92be7d574573\",\"webcompat-reporter@mozilla.org\":\"3dab7d63-52d4-429a-8a58-acff43966fb7\",\"webcompat@mozilla.org\":\"5d10a437-77f1-4964-ad51-1f77bc0ad0ba\",\"default-theme@mozilla.org\":\"46ba1509-48fc-47e1-a41d-57cac43e725e\",\"google@search.mozilla.org\":\"3d3e5c13-ff70-45f3-93f3-e19c5fbcda90\",\"amazondotcom@search.mozilla.org\":\"ff215866-24b0-461e-9e2b-67af5ed61b39\",\"bing@search.mozilla.org\":\"bcadedac-d01e-484c-9dd8-635c4512c6e6\",\"ddg@search.mozilla.org\":\"f94cde5e-07e3-4db8-ae24-dd6fc0dd0c6d\",\"ebay@search.mozilla.org\":\"0e3c00c3-9e07-422b-aaf3-140e12143280\",\"twitter@search.mozilla.org\":\"719ab620-c0de-44db-b543-6a4d3ead9827\",\"wikipedia@search.mozilla.org\":\"2c858deb-09ed-4d07-9957-0466b7f7dc59\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("permissions.eventTelemetry.salt", "{9f16d38b-9b1a-4298-ad18-9518f70b3328}");
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "3df3949a-1ffc-463a-b0af-8890f244d779");
user_pref("security.sandbox.plugin.tempDirSuffix", "1b503496-6d42-41f0-a8c2-451f214d1110");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1578994083);
user_pref("toolkit.telemetry.cachedClientID", "5ca6e8cd-f0a7-4737-a70a-8dd19619d8ce");
user_pref("toolkit.telemetry.previousBuildID", "20200107212822");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
