days_to_crawl: 14 
loop_interval_for_new_keyword_accepted: 2
maximum_topic_display_length: 20
crawling_list: []
running_path: ~/docbao_crawler/
number_of_trending_keywords: 25
number_of_hot_keywords: 2000
minimum_topic_length: 4
display_timezone: Asia/Ho_Chi_Minh
hub_href: ''
minimum_keyword_length_for_fast_growing_keyword_accepted: 2
crawling_interval: 15
minimum_freq_for_more_than_two_length_keyword_appear_in_hot_keywords: 5
minimum_freq_series_for_fast_growing_keyword_accepted: 2
max_crawler: 5
category_list:
- chính trị:
    index: 1
    filename: category/chinh_tri.txt
- Kinh Tế:
    index: 2
    filename: category/kinh_te.txt
- Xã Hội:
    index: 3
    filename: category/xa_hoi.txt
- An Ninh:
    index: 4
    filename: category/an_ninh.txt
- Quốc Phòng:
    index: 5
    filename: category/quoc_phong.txt
- Văn Hoá:
    index: 6
    filename: category/van_hoa.txt
- Giáo Dục:
    index: 7
    filename: category/giao_duc.txt
- Thể Thao:
    index: 8
    filename: category/the_thao.txt
- Giải Trí:
    index: 9
    filename: category/giai_tri.txt
- Công nghệ:
    index: 10
    filename: category/cong_nghe.txt
- Giao Thông:
    index: 11
    filename: category/giao_thong.txt
- Quốc gia:
    index: 12
    filename: category/quoc_gia.txt
- Địa danh:
    index: 13
    filename: category/dia_danh.txt
- Sự kiện:
    index: 14
    filename: category/su_kien.txt
- Nhân vật:
    index: 15
    filename: category/nhan_vat.txt
use_CDN: true
waiting_time_between_each_crawl: 3
trending_duration: 720
minimum_publish_speed: 600
minimum_freq_for_two_length_keyword_appear_in_hot_keywords: 2
maximum_url_to_visit_each_turn: 15
minimum_weight: 0.002
timeout: 500
hub_title: Theo Dõi Tin Tức Mùa Thi THPT Quốc gia 2019
minimum_freq_for_new_keyword_accepted: 1
mininum_freq_for_new_keyword_accepted: 1
minimum_freq_for_fast_growing_keyword_accepted: 3
