// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.normandy.user_id", "fb1c3761-d712-4bb4-b31b-8bcda84e541d");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1578993891);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1578993921);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 16885);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1578993861);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 89);
user_pref("browser.newtabpage.activity-stream.impressionId", "{6421f550-3414-4371-8ffe-34992355c38c}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1578993887263");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1578995683263");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1578993865391");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1578997465391");
user_pref("browser.search.region", "VN");
user_pref("browser.slowStartup.averageTime", 46910);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200107212822");
user_pref("browser.startup.homepage_override.mstone", "72.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1578993862);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1578993863940");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "72.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "daf312a9dabe47529b24390cd66143bb");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "72.0.1");
user_pref("extensions.lastPlatformVersion", "72.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"3263b34f-5f6e-421d-8c09-168341aef8da\",\"formautofill@mozilla.org\":\"ae7714ac-41e1-4cfe-8f07-c5bb700318d8\",\"screenshots@mozilla.org\":\"34df0ddb-f611-4f2e-a00c-eed3b0345fd5\",\"webcompat-reporter@mozilla.org\":\"8c63ccd3-4a6c-4860-a6d2-c933943106d0\",\"webcompat@mozilla.org\":\"5ef579ad-dec1-48ba-a4ae-7f2d2a7f2596\",\"default-theme@mozilla.org\":\"cd235c71-8459-40ec-8f22-870aeeb70786\",\"google@search.mozilla.org\":\"d92d8ad2-154a-4b95-90ad-04edc8b18aee\",\"amazondotcom@search.mozilla.org\":\"84d11be5-f8b5-4f08-b498-01cf327828ad\",\"bing@search.mozilla.org\":\"de4b60d6-4ecd-4b67-bc28-b1887bb7297d\",\"ddg@search.mozilla.org\":\"5aedb033-1c31-4ea4-b4b7-9627cdc9168d\",\"ebay@search.mozilla.org\":\"9e8dbe31-a900-4c48-aab8-80128625ebf9\",\"twitter@search.mozilla.org\":\"23e007eb-488e-4cf8-a2c9-3d6e248baa1a\",\"wikipedia@search.mozilla.org\":\"8c3fc262-6929-44f4-8873-13ec1070873f\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("permissions.eventTelemetry.salt", "{6cd61b8d-20ed-4aae-af33-032baca9e2a1}");
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "5b6f12fc-bf8f-44f5-bfb0-fb422b2ef4bf");
user_pref("security.sandbox.plugin.tempDirSuffix", "30012ecd-60de-4b9d-9c5f-144e43164a0c");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1578993860);
user_pref("toolkit.telemetry.cachedClientID", "92864028-6b03-4292-8130-5fc4cd07572d");
user_pref("toolkit.telemetry.previousBuildID", "20200107212822");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
