// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1578993985);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1578994015);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 14349);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1578993954);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 89);
user_pref("browser.newtabpage.activity-stream.impressionId", "{8595e0e9-9165-494f-b5c0-95766c80c9af}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1578993997779");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1578995795779");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1578993959088");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1578997559088");
user_pref("browser.search.region", "VN");
user_pref("browser.slowStartup.averageTime", 22899);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200107212822");
user_pref("browser.startup.homepage_override.mstone", "72.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1578993956);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1578993957385");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "72.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "02b18dae02984768ad1ab96ff8ef9a3d");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "72.0.1");
user_pref("extensions.lastPlatformVersion", "72.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"01914d4c-c6e9-4762-a5ac-f3ea2323321e\",\"formautofill@mozilla.org\":\"093e4a96-a9c2-421b-83e5-89d5daff8cfe\",\"screenshots@mozilla.org\":\"9b7f3c09-8304-4ea7-bd6b-6bc8c5d4eadb\",\"webcompat-reporter@mozilla.org\":\"cc4d90ac-68fa-4a03-acc7-72d1b2843edd\",\"webcompat@mozilla.org\":\"05b7cf48-aa1b-47fa-9c49-fc556d135135\",\"default-theme@mozilla.org\":\"46283cc9-e3d5-46d2-9c8a-25b5a16baa7c\",\"google@search.mozilla.org\":\"3f343a22-2391-4cc6-8a57-df40f994c2cb\",\"amazondotcom@search.mozilla.org\":\"eeac2b9d-8fc0-478e-bdbb-61a97347fd2c\",\"bing@search.mozilla.org\":\"0b0ffbc6-1455-4ae9-ad0e-44ca7eab3af9\",\"ddg@search.mozilla.org\":\"c77ea955-d48c-4a32-8b25-3b919338df7c\",\"ebay@search.mozilla.org\":\"e480fe7e-13f8-4700-bbb2-8dd4e711fbe8\",\"twitter@search.mozilla.org\":\"7f52d42f-235e-4512-9c68-fc9108b83b0a\",\"wikipedia@search.mozilla.org\":\"46c81c49-b09b-4394-8bb3-d58099d11280\"}");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1578994011);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20200107212822");
user_pref("media.gmp-manager.lastCheck", 1578994010);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("permissions.eventTelemetry.salt", "{9b21765f-ba1e-4ff3-9342-c1fd39823dd2}");
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "273ff76e-5ed9-4e2c-af94-be236ff478fa");
user_pref("security.sandbox.plugin.tempDirSuffix", "2da3677d-3eb1-431a-bf12-26c8e0d225a0");
user_pref("services.blocklist.pinning.checked", 1578994009);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1578960089219\"");
user_pref("services.settings.last_update_seconds", 1578994009);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1578994009);
user_pref("services.settings.main.cfr-fxa.last_check", 1578994009);
user_pref("services.settings.main.cfr.last_check", 1578994009);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1578994009);
user_pref("services.settings.main.hijack-blocklists.last_check", 1578994009);
user_pref("services.settings.main.language-dictionaries.last_check", 1578994009);
user_pref("services.settings.main.public-suffix-list.last_check", 1578994009);
user_pref("services.settings.main.sites-classification.last_check", 1578994009);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1578994009);
user_pref("services.settings.main.whats-new-panel.last_check", 1578994009);
user_pref("services.settings.security.onecrl.checked", 1578994009);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1578993953);
user_pref("toolkit.telemetry.cachedClientID", "4ee9f3b4-1dab-4c27-85d3-0ac70072b811");
user_pref("toolkit.telemetry.previousBuildID", "20200107212822");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
