// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1578993678);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 11178);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1578993647);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 89);
user_pref("browser.newtabpage.activity-stream.impressionId", "{54956e5c-264f-4d80-a5cb-98233dd72bd1}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1578993677596");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1578995472596");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1578993651967");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1578997251967");
user_pref("browser.search.region", "VN");
user_pref("browser.slowStartup.averageTime", 51264);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200107212822");
user_pref("browser.startup.homepage_override.mstone", "72.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1578993649);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1578993650480");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "72.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "2c1ba88a51584234bf17e50d38916ae0");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "72.0.1");
user_pref("extensions.lastPlatformVersion", "72.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"3db3520b-1200-46e8-ac95-57e222673024\",\"formautofill@mozilla.org\":\"64b5def8-e091-44a3-8efb-6cc178bb7f6d\",\"screenshots@mozilla.org\":\"c0d8333e-4e5d-4305-968e-703d4c0e852b\",\"webcompat-reporter@mozilla.org\":\"c65d70d2-8683-423e-ac17-ceabb2c9a62a\",\"webcompat@mozilla.org\":\"93ee1031-501d-4c4c-bc45-6f67b8f4b9ea\",\"default-theme@mozilla.org\":\"9a3f1421-4c0c-4cdd-8314-6456385d38d1\",\"google@search.mozilla.org\":\"f223af03-8c0b-4d1d-bea7-562bcb396976\",\"amazondotcom@search.mozilla.org\":\"45f3bfc2-0f6b-4e04-85b9-c83c6d654fa1\",\"bing@search.mozilla.org\":\"094399d3-c8da-4698-8a9f-7c5e7ea0200b\",\"ddg@search.mozilla.org\":\"f0bd3f00-76f5-40a1-bdbc-97e60efc473d\",\"ebay@search.mozilla.org\":\"78da7a93-2a2d-4d57-86fa-d9d531344e8b\",\"twitter@search.mozilla.org\":\"0f7bef8b-dd35-4493-8389-d48998bcc8bc\",\"wikipedia@search.mozilla.org\":\"42719331-3fd7-488b-adb3-fdb334895815\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("permissions.eventTelemetry.salt", "{cd92fc25-0230-4fe1-b430-8c6817c630b7}");
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "c113aa41-ff97-4f13-b925-d7699e249f42");
user_pref("security.sandbox.plugin.tempDirSuffix", "7163239c-d0b9-4392-86f2-0ff018dfe24e");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1578993647);
user_pref("toolkit.telemetry.cachedClientID", "a921d586-f86d-4cc2-b01b-1a002984f265");
user_pref("toolkit.telemetry.previousBuildID", "20200107212822");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
