// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.normandy.user_id", "47526a55-4d37-4d10-8212-6328667dadc9");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1578993315);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1578993345);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 17091);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1578993285);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 89);
user_pref("browser.newtabpage.activity-stream.impressionId", "{1f74ac77-a8fa-4178-88af-6bec6dd2b3a5}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1578993320588");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1578995134588");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1578993289785");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1578996889785");
user_pref("browser.search.region", "VN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200107212822");
user_pref("browser.slowStartup.averageTime", 35000);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20200107212822");
user_pref("browser.startup.homepage_override.mstone", "72.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1578993361);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1578993287985");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "72.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "1b9c5ece72c9492c821985d44209b141");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200107212822");
user_pref("extensions.lastAppVersion", "72.0.1");
user_pref("extensions.lastPlatformVersion", "72.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"fcba631c-8e7f-4dc0-9f73-90b52b474155\",\"formautofill@mozilla.org\":\"4ba8b8e9-27d5-451c-97f2-eff3360a3b69\",\"screenshots@mozilla.org\":\"621b49c2-d6cb-4bda-a842-57d34ef3aa63\",\"webcompat-reporter@mozilla.org\":\"a4361a97-bb4e-482a-9eb3-cf8d963eaf60\",\"webcompat@mozilla.org\":\"7f0d215a-0556-4c48-97d7-59ed8307d518\",\"default-theme@mozilla.org\":\"f9c1bf95-be01-4bc1-accb-fd5756a4d0c1\",\"google@search.mozilla.org\":\"38f3814b-1d68-4737-9f19-f6c497d6dab2\",\"amazondotcom@search.mozilla.org\":\"4fa24d8b-0be3-4f3e-bf74-0e3624b7c2a7\",\"bing@search.mozilla.org\":\"ea178c9f-29a1-431d-a523-30daac23d8b5\",\"ddg@search.mozilla.org\":\"a08aa2fe-8719-4b13-8dca-872da0948ad1\",\"ebay@search.mozilla.org\":\"fa2afa9b-ca6c-4bde-9503-75bfd4a1e222\",\"twitter@search.mozilla.org\":\"acb80057-20e9-43af-af45-aaecf82bcdbf\",\"wikipedia@search.mozilla.org\":\"77b9abaf-3805-4f2b-bed0-34756c432aca\"}");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1578993316);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20200107212822");
user_pref("media.gmp-manager.lastCheck", 1578993316);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("permissions.eventTelemetry.salt", "{07afcf14-33b6-4013-b923-a91adbb16123}");
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "b9a72c16-b99e-436f-8845-7d520238f83a");
user_pref("security.sandbox.plugin.tempDirSuffix", "cd6a4844-9116-4b08-b77e-0275a2cc5090");
user_pref("services.blocklist.pinning.checked", 1578993323);
user_pref("services.settings.clock_skew_seconds", -8);
user_pref("services.settings.last_etag", "\"1578960089219\"");
user_pref("services.settings.last_update_seconds", 1578993323);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1578993323);
user_pref("services.settings.main.cfr-fxa.last_check", 1578993323);
user_pref("services.settings.main.cfr.last_check", 1578993323);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1578993323);
user_pref("services.settings.main.hijack-blocklists.last_check", 1578993323);
user_pref("services.settings.main.language-dictionaries.last_check", 1578993323);
user_pref("services.settings.main.public-suffix-list.last_check", 1578993323);
user_pref("services.settings.main.sites-classification.last_check", 1578993323);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1578993323);
user_pref("services.settings.main.whats-new-panel.last_check", 1578993323);
user_pref("services.settings.security.onecrl.checked", 1578993323);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1578993360);
user_pref("toolkit.telemetry.cachedClientID", "8eaa9a16-505e-4d0d-8822-f535301df1a4");
user_pref("toolkit.telemetry.previousBuildID", "20200107212822");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
