// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1578994602);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 10251);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1578994572);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 89);
user_pref("browser.newtabpage.activity-stream.impressionId", "{349fdba4-1afb-4566-882a-843b1c75d191}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1578994576125");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1578998176125");
user_pref("browser.search.region", "VN");
user_pref("browser.slowStartup.averageTime", 24771);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200107212822");
user_pref("browser.startup.homepage_override.mstone", "72.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1578994573);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1578994574858");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "72.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "911b82d0f44c447f9900262ec975dfdd");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "72.0.1");
user_pref("extensions.lastPlatformVersion", "72.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"1a34e1c4-6a6c-404d-b23e-f526f3aa9eb0\",\"formautofill@mozilla.org\":\"a467e79b-9351-493d-8abc-32ad03a6f429\",\"screenshots@mozilla.org\":\"80942b8e-65cf-4ec2-92e4-e3bb9621bc5c\",\"webcompat-reporter@mozilla.org\":\"f496c443-dc17-45cc-9325-f1b817931f4a\",\"webcompat@mozilla.org\":\"1116f074-14e5-4a83-9385-0af175b98bf4\",\"default-theme@mozilla.org\":\"a990d0d8-f46d-425c-b4d1-ff7896979bbc\",\"google@search.mozilla.org\":\"9bd6e3cd-eaef-429c-be33-7c6382afcc19\",\"amazondotcom@search.mozilla.org\":\"9e370575-21f2-40d1-bcde-286ada8566f0\",\"bing@search.mozilla.org\":\"9a391edd-7d21-4584-aada-c9cac15f82a4\",\"ddg@search.mozilla.org\":\"1acf2626-a179-4af2-a8b2-a4235c56c0bb\",\"ebay@search.mozilla.org\":\"12147b50-d046-49da-8b9f-a6f455a328cf\",\"twitter@search.mozilla.org\":\"7d4504e3-794c-4ab9-9623-c6c48a7f447b\",\"wikipedia@search.mozilla.org\":\"f2c94192-5378-45c3-acec-537a5218ac72\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("permissions.eventTelemetry.salt", "{1a3f7ed0-f70c-4eed-8172-7c4f2724e87f}");
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "2b997af7-57a2-4a11-9a64-d4767182d357");
user_pref("security.sandbox.plugin.tempDirSuffix", "8bd07459-b7cf-4bc3-aea4-8381cede4a94");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1578994571);
user_pref("toolkit.telemetry.cachedClientID", "fc5a8bca-3b27-460b-a834-33153c5beb18");
user_pref("toolkit.telemetry.previousBuildID", "20200107212822");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
